// SPDX-FileCopyrightText: 2021 Open Networking Foundation <info@opennetworking.org>
// Copyright 2019 free5GC.org
//
// SPDX-License-Identifier: Apache-2.0

/*
 * Nsmf_EventExposure
 *
 * Session Management Event Exposure Service API
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package callback

import (
	"net/http"
	// "net/url"
	// "path"
	// "strings"

	"github.com/5GC-DEV/openapi-cdac"
	"github.com/5GC-DEV/openapi-cdac/models"
	"github.com/5GC-DEV/util-cdac/httpwrapper"
	"github.com/gin-gonic/gin"
	smf_context "github.com/omec-project/smf/context"
	"github.com/omec-project/smf/fsm"
	"github.com/omec-project/smf/logger"
	stats "github.com/omec-project/smf/metrics"
	"github.com/omec-project/smf/msgtypes/svcmsgtypes"
	"github.com/omec-project/smf/transaction"
)

// SubscriptionsPost -
/*func HTTPSmPolicyUpdateNotification(c *gin.Context) {
	var request models.SmPolicyNotification

	reqBody, err := c.GetRawData()
	if err != nil {
		logger.PduSessLog.Errorf("error reading body: %v", err)
	}

	err = openapi.Deserialize(&request, reqBody, c.ContentType())
	if err != nil {
		logger.PduSessLog.Errorln("deserialize request failed:", err)
		c.JSON(400, gin.H{"error": "invalid body"})
		return
	}

	// 1) Extract IMSI from ResourceUri
	imsi := extractIMSIFromResourceURI(request.ResourceUri)

	logger.PduSessLog.Infof("PCF CALLBACK ResourceUri=%s Parsed IMSI=%s",
		request.ResourceUri, imsi)

	// 2) Get all IMS contexts (optionally filtered by IMSI)
	matchedContexts := smf_context.GetSMContextsByDnnAndImsi("ims", imsi)

	if len(matchedContexts) == 0 {
		logger.PduSessLog.Errorf("No IMS SMContext found for IMSI=%s", imsi)
		c.JSON(404, gin.H{"error": "No matching IMS SMContext"})
		return
	}

	logger.PduSessLog.Infof("Applying PCF update to %d IMS sessions", len(matchedContexts))

	// 3) Apply update to each context
	for _, smCtx := range matchedContexts {
		logger.PduSessLog.Infof("Applying PCF update to SUPI=%s PDU=%d Ref=%s",
			smCtx.Supi, smCtx.PDUSessionID, smCtx.Ref)

		txn := transaction.NewTransaction(
			request,
			nil,
			svcmsgtypes.SmPolicyUpdateNotification,
		)

		txn.Ctxt = smCtx
		txn.CtxtKey = smCtx.Ref

		go txn.StartTxnLifeCycle(fsm.SmfTxnFsmHandle)
		<-txn.Status
	}

	c.Status(http.StatusNoContent)
}*/
func HTTPSmPolicyUpdateNotification(c *gin.Context) {
	var request models.SmPolicyNotification

	logger.PduSessLog.Infof("Received SmPolicyUpdateNotification HTTP request")

	reqBody, err := c.GetRawData()
	if err != nil {
		logger.PduSessLog.Errorf("Failed to read request body: %v", err)
		return
	}
	logger.PduSessLog.Infof("Raw request body: %s", string(reqBody))

	err = openapi.Deserialize(&request, reqBody, c.ContentType())
	if err != nil {
		logger.PduSessLog.Errorf("Failed to deserialize SmPolicyNotification: %v", err)
		return
	}
	logger.PduSessLog.Infof("Successfully deserialized SmPolicyNotification: %+v", request)

	reqWrapper := httpwrapper.NewRequest(c.Request, request)
	reqWrapper.Params["smContextRef"] = c.Params.ByName("smContextRef")

	smContextRef := reqWrapper.Params["smContextRef"]
	logger.PduSessLog.Infof("HTTPSmPolicyUpdateNotification received for smContextRef: %v", smContextRef)

	logger.PduSessLog.Infof("Creating transaction for SmPolicyUpdateNotification")

	txn := transaction.NewTransaction(reqWrapper.Body.(models.SmPolicyNotification), nil, svcmsgtypes.SmPolicyUpdateNotification)
	txn.CtxtKey = smContextRef

	logger.PduSessLog.Infof("Transaction created. CtxtKey: %s, MsgType: %v", txn.CtxtKey, svcmsgtypes.SmPolicyUpdateNotification)

	logger.PduSessLog.Infof("Starting transaction lifecycle for smContextRef: %s", smContextRef)

	go txn.StartTxnLifeCycle(fsm.SmfTxnFsmHandle)

	logger.PduSessLog.Infof("Waiting for transaction completion for smContextRef: %s", smContextRef)

	<-txn.Status // wait for txn to complete

	logger.PduSessLog.Infof("Transaction completed for smContextRef: %s", smContextRef)

	HTTPResponse := txn.Rsp.(*httpwrapper.Response)

	logger.PduSessLog.Infof("Preparing HTTP response for smContextRef: %s, Status: %d", smContextRef, HTTPResponse.Status)

	for key, val := range HTTPResponse.Header {
		c.Header(key, val[0])
	}

	resBody, err := openapi.Serialize(HTTPResponse.Body, "application/json")
	if err != nil {
		logger.PduSessLog.Errorf("Failed to serialize response body: %v", err)
		return
	}

	_, err = c.Writer.Write(resBody)
	if err != nil {
		logger.PduSessLog.Errorf("Failed to write response body: %v", err)
	}

	logger.PduSessLog.Infof("Sending HTTP response for smContextRef: %s with status %d", smContextRef, HTTPResponse.Status)

	c.Status(HTTPResponse.Status)
}

// Helper function to extract IMSI from ResourceUri
/*func extractIMSIFromResourceURI(resourceURI string) string {
	u, err := url.Parse(resourceURI)
	if err != nil {
		return ""
	}

	base := path.Base(u.Path) // "imsi-001010000000001-6"

	// Remove last "-<pduSessionId>"
	if idx := strings.LastIndex(base, "-"); idx > 0 {
		base = base[:idx] // "imsi-001010000000001"
	}

	if !strings.HasPrefix(base, "imsi-") {
		return ""
	}

	return base
}*/

func SmPolicyControlTerminationRequestNotification(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

func N1N2FailureNotification(c *gin.Context) {
	logger.PduSessLog.Info("receive N1N2 Failure Notification")
	stats.IncrementN11MsgStats(smf_context.SMF_Self().NfInstanceID, string(svcmsgtypes.N1N2MessageTransferFailureNotification), "In", "", "")

	var request models.N1N2MsgTxfrFailureNotification

	req := httpwrapper.NewRequest(c.Request, request)

	req.Params["smContextRef"] = c.Params.ByName("smContextRef")

	smContextRef := req.Params["smContextRef"]
	txn := transaction.NewTransaction(req.Body.(models.N1N2MsgTxfrFailureNotification), nil, svcmsgtypes.N1N2MessageTransferFailureNotification)
	txn.CtxtKey = smContextRef
	go txn.StartTxnLifeCycle(fsm.SmfTxnFsmHandle)
	<-txn.Status

	stats.IncrementN11MsgStats(smf_context.SMF_Self().NfInstanceID, string(svcmsgtypes.N1N2MessageTransferFailureNotification), "Out", http.StatusText(http.StatusNoContent), "")
	c.Status(http.StatusNoContent)
}
