// Copyright 2019 free5GC.org
//
// SPDX-License-Identifier: Apache-2.0

/*
 * Nsmf_PDUSession
 *
 * SMF PDU Session Service
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package pdusession

import (
	"fmt"
	"net/http"
	"strings"

	"github.com/gin-gonic/gin"
	"github.com/omec-project/openapi"
	"github.com/omec-project/openapi/models"
	smf_context "github.com/omec-project/smf/context"
	"github.com/omec-project/smf/fsm"
	"github.com/omec-project/smf/logger"
	stats "github.com/omec-project/smf/metrics"
	"github.com/omec-project/smf/msgtypes/svcmsgtypes"
	"github.com/omec-project/smf/transaction"
	"github.com/omec-project/util/httpwrapper"
	mi "github.com/omec-project/util/metricinfo"
)

// HTTPPostSmContexts - Create SM Context
/*func HTTPPostSmContexts(c *gin.Context) {
	logger.PduSessLog.Infoln("receive create SM Context Request")
	var err error
	var request models.PostSmContextsRequest
	stats.IncrementN11MsgStats(smf_context.SMF_Self().NfInstanceID, string(svcmsgtypes.CreateSmContext), "In", "", "")
	err = stats.PublishMsgEvent(mi.Smf_msg_type_pdu_sess_create_req)
	if err != nil {
		logger.PduSessLog.Errorf("error: %v", err)
		return
	}

	request.JsonData = new(models.SmContextCreateData)

	s := strings.Split(c.GetHeader("Content-Type"), ";")
	switch s[0] {
	case "application/json":
		err = c.ShouldBindJSON(request.JsonData)
	case "multipart/related":
		err = c.ShouldBindWith(&request, openapi.MultipartRelatedBinding{})
	}

	if err != nil {
		problemDetail := "[Request Body] " + err.Error()
		rsp := models.ProblemDetails{
			Title:  "Malformed request syntax",
			Status: http.StatusBadRequest,
			Detail: problemDetail,
		}
		stats.IncrementN11MsgStats(smf_context.SMF_Self().NfInstanceID, string(svcmsgtypes.CreateSmContext), "Out", http.StatusText(http.StatusBadRequest), "Malformed")
		logger.PduSessLog.Errorln(problemDetail)
		c.JSON(http.StatusBadRequest, rsp)
		return
	}

	req := httpwrapper.NewRequest(c.Request, request)
	txn := transaction.NewTransaction(req.Body.(models.PostSmContextsRequest), nil, svcmsgtypes.CreateSmContext)

	go txn.StartTxnLifeCycle(fsm.SmfTxnFsmHandle)
	<-txn.Status // wait for txn to complete at SMF
	HTTPResponse := txn.Rsp.(*httpwrapper.Response)
	smContext := txn.Ctxt.(*smf_context.SMContext)
	errStr := ""
	if txn.Err != nil {
		errStr = txn.Err.Error()
	}

	// Http Response to AMF

	for key, val := range HTTPResponse.Header {
		c.Header(key, val[0])
	}
	stats.IncrementN11MsgStats(smf_context.SMF_Self().NfInstanceID, string(svcmsgtypes.CreateSmContext), "Out", http.StatusText(HTTPResponse.Status), errStr)
	switch HTTPResponse.Status {
	case http.StatusCreated,
		http.StatusBadRequest,
		http.StatusForbidden,
		http.StatusNotFound,
		http.StatusInternalServerError,
		http.StatusServiceUnavailable,
		http.StatusGatewayTimeout:
		c.Render(HTTPResponse.Status, openapi.MultipartRelatedRender{Data: HTTPResponse.Body})
	default:
		c.JSON(HTTPResponse.Status, HTTPResponse.Body)
	}

	go func(smContext *smf_context.SMContext) {
		var txn *transaction.Transaction
		if HTTPResponse.Status == http.StatusCreated {
			txn = transaction.NewTransaction(nil, nil, svcmsgtypes.PfcpSessCreate)
			txn.Ctxt = smContext
			go txn.StartTxnLifeCycle(fsm.SmfTxnFsmHandle)
			<-txn.Status
		} else {
			smf_context.RemoveSMContext(smContext.Ref)
		}
	}(smContext)
} */

func HTTPPostSmContexts(c *gin.Context) {
	logger.PduSessLog.Infoln("=== [Nsmf_PDUSession] Received Create SM Context Request ===")

	var err error
	var request models.PostSmContextsRequest
	stats.IncrementN11MsgStats(smf_context.SMF_Self().NfInstanceID, string(svcmsgtypes.CreateSmContext), "In", "", "")
	err = stats.PublishMsgEvent(mi.Smf_msg_type_pdu_sess_create_req)
	if err != nil {
		logger.PduSessLog.Errorf("Failed to publish SMF Msg Event: %v", err)
		return
	}

	request.JsonData = new(models.SmContextCreateData)

	// Detect Content-Type
	contentType := c.GetHeader("Content-Type")
	logger.PduSessLog.Infof("HTTP Content-Type: %s", contentType)

	s := strings.Split(contentType, ";")
	switch s[0] {
	case "application/json":
		logger.PduSessLog.Infoln("Binding request as application/json")
		err = c.ShouldBindJSON(request.JsonData)
	case "multipart/related":
		logger.PduSessLog.Infoln("Binding request as multipart/related")
		if err = c.ShouldBindWith(&request, openapi.MultipartRelatedBinding{}); err != nil {
			logger.PduSessLog.Errorf("Multipart bind failed: %v", err)
			rsp := models.ProblemDetails{
				Title:  "Malformed multipart request",
				Status: http.StatusBadRequest,
				Detail: err.Error(),
			}
			c.JSON(http.StatusBadRequest, rsp)
			return
		}
	default:
		logger.PduSessLog.Warnf("Unsupported Content-Type: %s", s[0])
		err = fmt.Errorf("unsupported Content-Type: %s", s[0])
	}

	if err != nil {
		problemDetail := "[Request Body] " + err.Error()
		rsp := models.ProblemDetails{
			Title:  "Malformed request syntax",
			Status: http.StatusBadRequest,
			Detail: problemDetail,
		}
		stats.IncrementN11MsgStats(smf_context.SMF_Self().NfInstanceID, string(svcmsgtypes.CreateSmContext), "Out", http.StatusText(http.StatusBadRequest), "Malformed")
		logger.PduSessLog.Errorf("Request binding failed: %v", problemDetail)
		c.JSON(http.StatusBadRequest, rsp)
		return
	}

	logger.PduSessLog.Infof("SM Context Create Request successfully parsed: %+v", request.JsonData)

	req := httpwrapper.NewRequest(c.Request, request)
	txn := transaction.NewTransaction(req.Body.(models.PostSmContextsRequest), nil, svcmsgtypes.CreateSmContext)
	logger.PduSessLog.Infof("Created transaction for SUPI [%s]", request.JsonData.Supi)

	go txn.StartTxnLifeCycle(fsm.SmfTxnFsmHandle)
	<-txn.Status // wait for txn to complete at SMF
	HTTPResponse := txn.Rsp.(*httpwrapper.Response)
	smContext := txn.Ctxt.(*smf_context.SMContext)
	errStr := ""
	if txn.Err != nil {
		errStr = txn.Err.Error()
		logger.PduSessLog.Errorf("Transaction failed: %v", errStr)
	} else {
		logger.PduSessLog.Infof("Transaction completed successfully for SUPI [%s], PDU Session ID [%d]",
			smContext.Supi, smContext.PDUSessionID)
	}

	// Http Response to AMF
	logger.PduSessLog.Infof("Sending HTTP Response to AMF with Status [%d]", HTTPResponse.Status)
	for key, val := range HTTPResponse.Header {
		c.Header(key, val[0])
		logger.PduSessLog.Debugf("Response Header: %s = %s", key, val[0])
	}

	stats.IncrementN11MsgStats(smf_context.SMF_Self().NfInstanceID, string(svcmsgtypes.CreateSmContext), "Out", http.StatusText(HTTPResponse.Status), errStr)

	switch HTTPResponse.Status {
	case http.StatusCreated,
		http.StatusBadRequest,
		http.StatusForbidden,
		http.StatusNotFound,
		http.StatusInternalServerError,
		http.StatusServiceUnavailable,
		http.StatusGatewayTimeout:
		logger.PduSessLog.Debugf("Rendering multipart response for Status [%d]", HTTPResponse.Status)
		c.Render(HTTPResponse.Status, openapi.MultipartRelatedRender{Data: HTTPResponse.Body})
	default:
		logger.PduSessLog.Debugf("Rendering JSON response for Status [%d]", HTTPResponse.Status)
		c.JSON(HTTPResponse.Status, HTTPResponse.Body)
	}

	// PFCP Session Create in background
	go func(smContext *smf_context.SMContext) {
		if HTTPResponse.Status == http.StatusCreated {
			logger.PduSessLog.Infof("Triggering PFCP Session Create for SUPI [%s], PDU Session ID [%d]",
				smContext.Supi, smContext.PDUSessionID)
			txn := transaction.NewTransaction(nil, nil, svcmsgtypes.PfcpSessCreate)
			txn.Ctxt = smContext
			go txn.StartTxnLifeCycle(fsm.SmfTxnFsmHandle)
			<-txn.Status
			logger.PduSessLog.Infof("PFCP Session Create Transaction finished for SUPI [%s], PDU Session ID [%d]",
				smContext.Supi, smContext.PDUSessionID)
		} else {
			logger.PduSessLog.Warnf("SM Context Create failed, removing SMContext Ref [%s]", smContext.Ref)
			smf_context.RemoveSMContext(smContext.Ref)
		}
	}(smContext)
}
