# SPDX-License-Identifier: Apache-2.0
# Copyright 2024 Intel Corporation
name: GitHub release and Docker images

on:
    workflow_dispatch:
    
jobs:
  docker-build-push-images:
    runs-on: ubuntu-latest
   
    env:
      REGISTRY: ghcr.io
      DOCKER_REGISTRY: ghcr.io/
      DOCKER_REPOSITORY: ios-mcn-core/
      RELEASE_VERSION: 0.0.3
       
      
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'

      - run: echo GIT_SHA_SHORT=$(git rev-parse --short HEAD) >> $GITHUB_ENV

      - uses: docker/login-action@v3.1.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.GHCRUSER }}
          password: ${{ secrets.GHCRPASS }}

      - name: Build and push "master-latest" Docker image
        env:
          DOCKER_TAG: iosmcn-smf-release-${{ env.RELEASE_VERSION }}
        run: |
          make docker-build
          make docker-push

      - name: Build and push "master-GIT_SHA" Docker image
        env:
          DOCKER_TAG: iosmcn-smf-release-${{ env.RELEASE_VERSION }}
        run: |
          make docker-build
          make docker-push
